-- Toluene Tech V2 — initial schema
-- Auto-generated by drizzle-kit from server/src/db/schema.ts
-- Apply with: npm run db:migrate (or npx drizzle-kit migrate --config server/drizzle.config.ts)

CREATE TYPE "public"."availability" AS ENUM('AVAILABLE', 'LIMITED', 'UNAVAILABLE');
CREATE TYPE "public"."project_status" AS ENUM('ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED');
CREATE TYPE "public"."publish_state" AS ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "public"."product_status" AS ENUM('IDEA', 'PROTOTYPE', 'IN_DEV', 'BETA', 'LIVE', 'ARCHIVED');
CREATE TYPE "public"."lab_category" AS ENUM('AI', 'EXPERIMENT', 'TOOL', 'RESEARCH');
CREATE TYPE "public"."lead_status" AS ENUM('NEW', 'CONTACTED', 'QUALIFIED', 'DISCOVERY', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST');
CREATE TYPE "public"."client_status" AS ENUM('ACTIVE', 'INACTIVE');
CREATE TYPE "public"."milestone_status" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'APPROVED');
CREATE TYPE "public"."task_status" AS ENUM('TODO', 'IN_PROGRESS', 'DONE', 'BLOCKED');
CREATE TYPE "public"."message_context" AS ENUM('PROJECT', 'LEAD', 'GENERAL');--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "admin_users" (
	"uid" varchar(128) PRIMARY KEY NOT NULL,
	"email" varchar(240) NOT NULL,
	"name" varchar(160),
	"role" varchar(30) DEFAULT 'ADMIN' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "assistant_messages" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"session_id" varchar(36) NOT NULL,
	"role" varchar(16) NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "assistant_sessions" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"anon_id" varchar(64) NOT NULL,
	"name" varchar(160),
	"email" varchar(240),
	"captured_lead_id" varchar(36),
	"intent" varchar(40),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_message_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "client_projects" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"client_id" varchar(36) NOT NULL,
	"public_project_id" varchar(36),
	"title" varchar(220) NOT NULL,
	"description" text,
	"status" "project_status" DEFAULT 'ACTIVE' NOT NULL,
	"progress" integer DEFAULT 0 NOT NULL,
	"start_date" timestamp with time zone,
	"due_date" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "clients" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"user_id" varchar(128),
	"name" varchar(160) NOT NULL,
	"email" varchar(240) NOT NULL,
	"phone" varchar(40),
	"company" varchar(180),
	"status" "client_status" DEFAULT 'ACTIVE' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "clients_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "faqs" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"question" text NOT NULL,
	"answer" text NOT NULL,
	"category" varchar(80),
	"order" integer DEFAULT 0 NOT NULL,
	"is_published" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "invoices" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"client_id" varchar(36) NOT NULL,
	"project_id" varchar(36),
	"number" varchar(40) NOT NULL,
	"amount_cents" integer NOT NULL,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"status" varchar(30) DEFAULT 'DRAFT' NOT NULL,
	"due_date" timestamp with time zone,
	"paid_at" timestamp with time zone,
	"pdf_r2_key" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "invoices_number_unique" UNIQUE("number")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "insights" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"slug" varchar(200) NOT NULL,
	"title" varchar(240) NOT NULL,
	"excerpt" text,
	"cover_image" varchar(500),
	"content" text NOT NULL,
	"author" varchar(120),
	"category" varchar(80),
	"tags" jsonb DEFAULT '[]'::jsonb,
	"publish_date" timestamp with time zone,
	"seo_title" varchar(200),
	"seo_description" text,
	"seo_og_image" varchar(500),
	"is_featured" boolean DEFAULT false NOT NULL,
	"is_draft" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "insights_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "lab_items" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"slug" varchar(160) NOT NULL,
	"title" varchar(220) NOT NULL,
	"description" text,
	"category" "lab_category" DEFAULT 'EXPERIMENT' NOT NULL,
	"tech" jsonb DEFAULT '[]'::jsonb,
	"demo_url" varchar(500),
	"status" varchar(40) DEFAULT 'active' NOT NULL,
	"screenshots" jsonb DEFAULT '[]'::jsonb,
	"published_at" timestamp with time zone,
	"is_published" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "lab_items_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "leads" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"ref" varchar(16) NOT NULL,
	"name" varchar(160) NOT NULL,
	"email" varchar(240) NOT NULL,
	"phone" varchar(40),
	"company" varchar(180),
	"services" jsonb DEFAULT '[]'::jsonb,
	"requirements" text,
	"budget" varchar(80),
	"timeline" varchar(80),
	"source" varchar(80),
	"notes" text,
	"status" "lead_status" DEFAULT 'NEW' NOT NULL,
	"follow_up_date" timestamp with time zone,
	"converted_client_id" varchar(36),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "leads_ref_unique" UNIQUE("ref")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "media" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"filename" varchar(240) NOT NULL,
	"r2_key" varchar(500) NOT NULL,
	"public_url" varchar(600) NOT NULL,
	"mime_type" varchar(120),
	"size_bytes" integer,
	"width" integer,
	"height" integer,
	"alt" varchar(300),
	"uploaded_by" varchar(128),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "media_r2_key_unique" UNIQUE("r2_key")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "messages" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"context_type" "message_context" DEFAULT 'GENERAL' NOT NULL,
	"context_id" varchar(36),
	"from_uid" varchar(128),
	"from_name" varchar(160) NOT NULL,
	"body" text NOT NULL,
	"attachments" jsonb DEFAULT '[]'::jsonb,
	"is_read" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "milestones" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"project_id" varchar(36) NOT NULL,
	"title" varchar(220) NOT NULL,
	"description" text,
	"due_date" timestamp with time zone,
	"status" "milestone_status" DEFAULT 'PENDING' NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "notifications" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"uid" varchar(128),
	"type" varchar(40) NOT NULL,
	"title" varchar(240) NOT NULL,
	"body" text,
	"link" varchar(300),
	"is_read" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pricing_plans" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"name" varchar(120) NOT NULL,
	"tagline" varchar(240),
	"price_monthly" integer,
	"price_one_time" integer,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"features" jsonb DEFAULT '[]'::jsonb,
	"cta_label" varchar(60) DEFAULT 'Start a project' NOT NULL,
	"cta_url" varchar(240),
	"is_featured" boolean DEFAULT false NOT NULL,
	"is_published" boolean DEFAULT true NOT NULL,
	"order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "products" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"slug" varchar(160) NOT NULL,
	"name" varchar(200) NOT NULL,
	"description" text,
	"logo" varchar(500),
	"screenshots" jsonb DEFAULT '[]'::jsonb,
	"features" jsonb DEFAULT '[]'::jsonb,
	"tech_stack" jsonb DEFAULT '[]'::jsonb,
	"status" "product_status" DEFAULT 'IDEA' NOT NULL,
	"demo_url" varchar(500),
	"website_url" varchar(500),
	"case_study_url" varchar(500),
	"is_published" boolean DEFAULT false NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "products_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "project_files" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"project_id" varchar(36) NOT NULL,
	"uploaded_by" varchar(128),
	"filename" varchar(240) NOT NULL,
	"r2_key" varchar(500) NOT NULL,
	"size_bytes" integer,
	"mime_type" varchar(120),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "projects" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"slug" varchar(160) NOT NULL,
	"title" varchar(220) NOT NULL,
	"client_name" varchar(200),
	"client_logo" varchar(500),
	"role" varchar(120),
	"platform" varchar(80),
	"framework" varchar(80),
	"completion_date" timestamp with time zone,
	"status" "project_status" DEFAULT 'ACTIVE' NOT NULL,
	"cover_image" varchar(500),
	"gallery" jsonb DEFAULT '[]'::jsonb,
	"video_url" varchar(500),
	"challenge" text,
	"objective" text,
	"solution" text,
	"features" jsonb DEFAULT '[]'::jsonb,
	"process" jsonb DEFAULT '[]'::jsonb,
	"results" text,
	"metrics" jsonb DEFAULT '[]'::jsonb,
	"live_url" varchar(500),
	"github_url" varchar(500),
	"app_store_url" varchar(500),
	"play_store_url" varchar(500),
	"service_ids" jsonb DEFAULT '[]'::jsonb,
	"is_published" boolean DEFAULT false NOT NULL,
	"is_featured" boolean DEFAULT false NOT NULL,
	"has_client_permission" boolean DEFAULT false NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"seo_title" varchar(200),
	"seo_description" text,
	"seo_og_image" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "projects_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "services" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"slug" varchar(120) NOT NULL,
	"title" varchar(200) NOT NULL,
	"short_description" text NOT NULL,
	"long_description" text,
	"icon" varchar(60),
	"capabilities" jsonb DEFAULT '[]'::jsonb,
	"related_project_ids" jsonb DEFAULT '[]'::jsonb,
	"is_published" boolean DEFAULT false NOT NULL,
	"is_featured" boolean DEFAULT false NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"seo_title" varchar(200),
	"seo_description" text,
	"seo_og_image" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "services_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "site_settings" (
	"key" varchar(64) PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tasks" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"project_id" varchar(36) NOT NULL,
	"milestone_id" varchar(36),
	"title" varchar(240) NOT NULL,
	"description" text,
	"status" "task_status" DEFAULT 'TODO' NOT NULL,
	"assignee" varchar(120),
	"due_date" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "testimonials" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"name" varchar(160) NOT NULL,
	"role" varchar(120),
	"company" varchar(160),
	"photo" varchar(500),
	"testimonial" text NOT NULL,
	"related_project_id" varchar(36),
	"is_featured" boolean DEFAULT false NOT NULL,
	"is_published" boolean DEFAULT false NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "am_sess_idx" ON "assistant_messages"("session_id");
--> statement-breakpoint
CREATE INDEX "as_anon_idx" ON "assistant_sessions"("anon_id");
--> statement-breakpoint
CREATE INDEX "cp_client_idx" ON "client_projects"("client_id");
--> statement-breakpoint
CREATE INDEX "lead_email_idx" ON "leads"("email");
--> statement-breakpoint
CREATE INDEX "lead_status_idx" ON "leads"("status");
--> statement-breakpoint
CREATE INDEX "msg_ctx_idx" ON "messages"("context_type","context_id");
--> statement-breakpoint
CREATE INDEX "ms_proj_idx" ON "milestones"("project_id");
--> statement-breakpoint
CREATE INDEX "n_uid_idx" ON "notifications"("uid");
--> statement-breakpoint
CREATE INDEX "pf_proj_idx" ON "project_files"("project_id");
--> statement-breakpoint
CREATE INDEX "prj_slug_idx" ON "projects"("slug");
--> statement-breakpoint
CREATE INDEX "svc_slug_idx" ON "services"("slug");
--> statement-breakpoint
CREATE INDEX "tk_proj_idx" ON "tasks"("project_id");
