-- =====================================================================
-- Toluene Tech — NEON STAGING MIGRATIONS (ALL-IN-ONE, idempotent)
--
-- INSTRUCTIONS (Neon Console → SQL Editor):
--   1. Open https://console.neon.tech → select your staging project → SQL Editor
--   2. Open a new query against the `neondb` database
--   3. Paste this entire file (it is idempotent — safe to run repeatedly)
--   4. Click Run
--
-- This file concatenates server/drizzle/0000..0004 plus __migrations
-- tracking plus the seed step. It is wrapped in a single transaction;
-- if anything fails, nothing is applied.
-- =====================================================================

BEGIN;

-- Tracker table ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS __migrations (
  tag text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

-- Helper so we can apply each migration inside the same transaction
-- without re-running already-applied migrations.
CREATE OR REPLACE FUNCTION __apply_migration(p_tag text, p_sql text)
RETURNS void AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM __migrations WHERE tag = p_tag) THEN
    EXECUTE p_sql;
    INSERT INTO __migrations (tag) VALUES (p_tag);
    RAISE NOTICE 'APPLIED %', p_tag;
  ELSE
    RAISE NOTICE 'SKIPPED % (already applied)', p_tag;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- ==== 0000_bouncy_warbound ====
SELECT __apply_migration('0000_bouncy_warbound', $mig$
-- Toluene Tech V2 — initial schema
-- Auto-generated by drizzle-kit from server/src/db/schema.ts
-- Apply with: npm run db:migrate (or npx drizzle-kit migrate --config server/drizzle.config.ts)

CREATE TYPE "public"."availability" AS ENUM('AVAILABLE', 'LIMITED', 'UNAVAILABLE');
CREATE TYPE "public"."project_status" AS ENUM('ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED');
CREATE TYPE "public"."publish_state" AS ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "public"."product_status" AS ENUM('IDEA', 'PROTOTYPE', 'IN_DEV', 'BETA', 'LIVE', 'ARCHIVED');
CREATE TYPE "public"."lab_category" AS ENUM('AI', 'EXPERIMENT', 'TOOL', 'RESEARCH');
CREATE TYPE "public"."lead_status" AS ENUM('NEW', 'CONTACTED', 'QUALIFIED', 'DISCOVERY', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST');
CREATE TYPE "public"."client_status" AS ENUM('ACTIVE', 'INACTIVE');
CREATE TYPE "public"."milestone_status" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'APPROVED');
CREATE TYPE "public"."task_status" AS ENUM('TODO', 'IN_PROGRESS', 'DONE', 'BLOCKED');
CREATE TYPE "public"."message_context" AS ENUM('PROJECT', 'LEAD', 'GENERAL');--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "admin_users" (
	"uid" varchar(128) PRIMARY KEY NOT NULL,
	"email" varchar(240) NOT NULL,
	"name" varchar(160),
	"role" varchar(30) DEFAULT 'ADMIN' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "assistant_messages" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"session_id" varchar(36) NOT NULL,
	"role" varchar(16) NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "assistant_sessions" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"anon_id" varchar(64) NOT NULL,
	"name" varchar(160),
	"email" varchar(240),
	"captured_lead_id" varchar(36),
	"intent" varchar(40),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_message_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "client_projects" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"client_id" varchar(36) NOT NULL,
	"public_project_id" varchar(36),
	"title" varchar(220) NOT NULL,
	"description" text,
	"status" "project_status" DEFAULT 'ACTIVE' NOT NULL,
	"progress" integer DEFAULT 0 NOT NULL,
	"start_date" timestamp with time zone,
	"due_date" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "clients" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"user_id" varchar(128),
	"name" varchar(160) NOT NULL,
	"email" varchar(240) NOT NULL,
	"phone" varchar(40),
	"company" varchar(180),
	"status" "client_status" DEFAULT 'ACTIVE' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "clients_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "faqs" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"question" text NOT NULL,
	"answer" text NOT NULL,
	"category" varchar(80),
	"order" integer DEFAULT 0 NOT NULL,
	"is_published" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "invoices" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"client_id" varchar(36) NOT NULL,
	"project_id" varchar(36),
	"number" varchar(40) NOT NULL,
	"amount_cents" integer NOT NULL,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"status" varchar(30) DEFAULT 'DRAFT' NOT NULL,
	"due_date" timestamp with time zone,
	"paid_at" timestamp with time zone,
	"pdf_r2_key" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "invoices_number_unique" UNIQUE("number")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "insights" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"slug" varchar(200) NOT NULL,
	"title" varchar(240) NOT NULL,
	"excerpt" text,
	"cover_image" varchar(500),
	"content" text NOT NULL,
	"author" varchar(120),
	"category" varchar(80),
	"tags" jsonb DEFAULT '[]'::jsonb,
	"publish_date" timestamp with time zone,
	"seo_title" varchar(200),
	"seo_description" text,
	"seo_og_image" varchar(500),
	"is_featured" boolean DEFAULT false NOT NULL,
	"is_draft" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "insights_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "lab_items" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"slug" varchar(160) NOT NULL,
	"title" varchar(220) NOT NULL,
	"description" text,
	"category" "lab_category" DEFAULT 'EXPERIMENT' NOT NULL,
	"tech" jsonb DEFAULT '[]'::jsonb,
	"demo_url" varchar(500),
	"status" varchar(40) DEFAULT 'active' NOT NULL,
	"screenshots" jsonb DEFAULT '[]'::jsonb,
	"published_at" timestamp with time zone,
	"is_published" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "lab_items_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "leads" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"ref" varchar(16) NOT NULL,
	"name" varchar(160) NOT NULL,
	"email" varchar(240) NOT NULL,
	"phone" varchar(40),
	"company" varchar(180),
	"services" jsonb DEFAULT '[]'::jsonb,
	"requirements" text,
	"budget" varchar(80),
	"timeline" varchar(80),
	"source" varchar(80),
	"notes" text,
	"status" "lead_status" DEFAULT 'NEW' NOT NULL,
	"follow_up_date" timestamp with time zone,
	"converted_client_id" varchar(36),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "leads_ref_unique" UNIQUE("ref")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "media" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"filename" varchar(240) NOT NULL,
	"r2_key" varchar(500) NOT NULL,
	"public_url" varchar(600) NOT NULL,
	"mime_type" varchar(120),
	"size_bytes" integer,
	"width" integer,
	"height" integer,
	"alt" varchar(300),
	"uploaded_by" varchar(128),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "media_r2_key_unique" UNIQUE("r2_key")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "messages" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"context_type" "message_context" DEFAULT 'GENERAL' NOT NULL,
	"context_id" varchar(36),
	"from_uid" varchar(128),
	"from_name" varchar(160) NOT NULL,
	"body" text NOT NULL,
	"attachments" jsonb DEFAULT '[]'::jsonb,
	"is_read" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "milestones" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"project_id" varchar(36) NOT NULL,
	"title" varchar(220) NOT NULL,
	"description" text,
	"due_date" timestamp with time zone,
	"status" "milestone_status" DEFAULT 'PENDING' NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "notifications" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"uid" varchar(128),
	"type" varchar(40) NOT NULL,
	"title" varchar(240) NOT NULL,
	"body" text,
	"link" varchar(300),
	"is_read" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pricing_plans" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"name" varchar(120) NOT NULL,
	"tagline" varchar(240),
	"price_monthly" integer,
	"price_one_time" integer,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"features" jsonb DEFAULT '[]'::jsonb,
	"cta_label" varchar(60) DEFAULT 'Start a project' NOT NULL,
	"cta_url" varchar(240),
	"is_featured" boolean DEFAULT false NOT NULL,
	"is_published" boolean DEFAULT true NOT NULL,
	"order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "products" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"slug" varchar(160) NOT NULL,
	"name" varchar(200) NOT NULL,
	"description" text,
	"logo" varchar(500),
	"screenshots" jsonb DEFAULT '[]'::jsonb,
	"features" jsonb DEFAULT '[]'::jsonb,
	"tech_stack" jsonb DEFAULT '[]'::jsonb,
	"status" "product_status" DEFAULT 'IDEA' NOT NULL,
	"demo_url" varchar(500),
	"website_url" varchar(500),
	"case_study_url" varchar(500),
	"is_published" boolean DEFAULT false NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "products_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "project_files" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"project_id" varchar(36) NOT NULL,
	"uploaded_by" varchar(128),
	"filename" varchar(240) NOT NULL,
	"r2_key" varchar(500) NOT NULL,
	"size_bytes" integer,
	"mime_type" varchar(120),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "projects" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"slug" varchar(160) NOT NULL,
	"title" varchar(220) NOT NULL,
	"client_name" varchar(200),
	"client_logo" varchar(500),
	"role" varchar(120),
	"platform" varchar(80),
	"framework" varchar(80),
	"completion_date" timestamp with time zone,
	"status" "project_status" DEFAULT 'ACTIVE' NOT NULL,
	"cover_image" varchar(500),
	"gallery" jsonb DEFAULT '[]'::jsonb,
	"video_url" varchar(500),
	"challenge" text,
	"objective" text,
	"solution" text,
	"features" jsonb DEFAULT '[]'::jsonb,
	"process" jsonb DEFAULT '[]'::jsonb,
	"results" text,
	"metrics" jsonb DEFAULT '[]'::jsonb,
	"live_url" varchar(500),
	"github_url" varchar(500),
	"app_store_url" varchar(500),
	"play_store_url" varchar(500),
	"service_ids" jsonb DEFAULT '[]'::jsonb,
	"is_published" boolean DEFAULT false NOT NULL,
	"is_featured" boolean DEFAULT false NOT NULL,
	"has_client_permission" boolean DEFAULT false NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"seo_title" varchar(200),
	"seo_description" text,
	"seo_og_image" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "projects_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "services" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"slug" varchar(120) NOT NULL,
	"title" varchar(200) NOT NULL,
	"short_description" text NOT NULL,
	"long_description" text,
	"icon" varchar(60),
	"capabilities" jsonb DEFAULT '[]'::jsonb,
	"related_project_ids" jsonb DEFAULT '[]'::jsonb,
	"is_published" boolean DEFAULT false NOT NULL,
	"is_featured" boolean DEFAULT false NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"seo_title" varchar(200),
	"seo_description" text,
	"seo_og_image" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "services_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "site_settings" (
	"key" varchar(64) PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tasks" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"project_id" varchar(36) NOT NULL,
	"milestone_id" varchar(36),
	"title" varchar(240) NOT NULL,
	"description" text,
	"status" "task_status" DEFAULT 'TODO' NOT NULL,
	"assignee" varchar(120),
	"due_date" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "testimonials" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"name" varchar(160) NOT NULL,
	"role" varchar(120),
	"company" varchar(160),
	"photo" varchar(500),
	"testimonial" text NOT NULL,
	"related_project_id" varchar(36),
	"is_featured" boolean DEFAULT false NOT NULL,
	"is_published" boolean DEFAULT false NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "am_sess_idx" ON "assistant_messages"("session_id");
--> statement-breakpoint
CREATE INDEX "as_anon_idx" ON "assistant_sessions"("anon_id");
--> statement-breakpoint
CREATE INDEX "cp_client_idx" ON "client_projects"("client_id");
--> statement-breakpoint
CREATE INDEX "lead_email_idx" ON "leads"("email");
--> statement-breakpoint
CREATE INDEX "lead_status_idx" ON "leads"("status");
--> statement-breakpoint
CREATE INDEX "msg_ctx_idx" ON "messages"("context_type","context_id");
--> statement-breakpoint
CREATE INDEX "ms_proj_idx" ON "milestones"("project_id");
--> statement-breakpoint
CREATE INDEX "n_uid_idx" ON "notifications"("uid");
--> statement-breakpoint
CREATE INDEX "pf_proj_idx" ON "project_files"("project_id");
--> statement-breakpoint
CREATE INDEX "prj_slug_idx" ON "projects"("slug");
--> statement-breakpoint
CREATE INDEX "svc_slug_idx" ON "services"("slug");
--> statement-breakpoint
CREATE INDEX "tk_proj_idx" ON "tasks"("project_id");
$mig$);

-- ==== 0001_tearful_millenium_guard ====
SELECT __apply_migration('0001_tearful_millenium_guard', $mig$
CREATE TYPE "public"."audit_action" AS ENUM('LOGIN_SUCCESS', 'LOGIN_FAILURE', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'PUBLISH', 'UNPUBLISH', 'AI_CONFIG_UPDATE', 'MODEL_CHANGE', 'SETTINGS_UPDATE', 'FILE_UPLOAD', 'FILE_DELETE', 'PERMISSION_CHANGE', 'PASSWORD_CHANGE', 'ACCESS_CODE_GENERATED', 'LEAD_CONVERT');--> statement-breakpoint
CREATE TYPE "public"."file_visibility" AS ENUM('PUBLIC', 'PRIVATE');--> statement-breakpoint
CREATE TABLE "ai_usage" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"surface" varchar(24) NOT NULL,
	"model" varchar(160) NOT NULL,
	"fallback_used" boolean DEFAULT false NOT NULL,
	"reason_fallback" varchar(80),
	"input_tokens" integer,
	"output_tokens" integer,
	"latency_ms" integer,
	"error_code" varchar(80),
	"tool_calls" jsonb DEFAULT '[]'::jsonb,
	"session_id" varchar(36),
	"client_id" varchar(36),
	"ip" varchar(64),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_logs" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"actor_type" varchar(16) NOT NULL,
	"actor_id" varchar(128),
	"actor_role" varchar(32),
	"action" "audit_action" NOT NULL,
	"entity" varchar(64) NOT NULL,
	"entity_id" varchar(36),
	"success" boolean DEFAULT true NOT NULL,
	"ip" varchar(64),
	"ua" varchar(300),
	"meta" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "access_code" varchar(32);--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "last_login_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "media" ADD COLUMN "visibility" "file_visibility" DEFAULT 'PUBLIC' NOT NULL;--> statement-breakpoint
ALTER TABLE "media" ADD COLUMN "role" varchar(60);--> statement-breakpoint
ALTER TABLE "media" ADD COLUMN "project_id" varchar(36);--> statement-breakpoint
ALTER TABLE "media" ADD COLUMN "client_id" varchar(36);--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "client_id" varchar(36);--> statement-breakpoint
ALTER TABLE "project_files" ADD COLUMN "client_id" varchar(36);--> statement-breakpoint
ALTER TABLE "project_files" ADD COLUMN "uploaded_by_role" varchar(16);--> statement-breakpoint
ALTER TABLE "project_files" ADD COLUMN "visibility" "file_visibility" DEFAULT 'PRIVATE' NOT NULL;--> statement-breakpoint
CREATE INDEX "ai_surf_idx" ON "ai_usage" USING btree ("surface","created_at");--> statement-breakpoint
CREATE INDEX "ai_model_idx" ON "ai_usage" USING btree ("model");--> statement-breakpoint
CREATE INDEX "ai_sess_idx" ON "ai_usage" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "al_actor_idx" ON "audit_logs" USING btree ("actor_type","actor_id");--> statement-breakpoint
CREATE INDEX "al_entity_idx" ON "audit_logs" USING btree ("entity","entity_id");--> statement-breakpoint
CREATE INDEX "al_ts_idx" ON "audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "cl_email_idx" ON "clients" USING btree ("email");--> statement-breakpoint
CREATE UNIQUE INDEX "media_r2_idx" ON "media" USING btree ("r2_key");--> statement-breakpoint
CREATE INDEX "media_proj_idx" ON "media" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "n_c_idx" ON "notifications" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "pf_client_idx" ON "project_files" USING btree ("client_id");--> statement-breakpoint
ALTER TABLE "clients" ADD CONSTRAINT "clients_email_unique" UNIQUE("email");$mig$);

-- ==== 0002_foreign_keys_manual ====
SELECT __apply_migration('0002_foreign_keys_manual', $mig$
-- FOREIGN KEYS (APPLY AFTER DATA INTEGRITY AUDIT)
--
-- This script is NOT applied automatically by drizzle-kit migrate. It contains
-- foreign-key constraints that will FAIL if orphan records exist. Before running
-- this in production:
--   1. Run scripts/audit-orphans.sh (or the SQL below) to report orphans.
--   2. Either soft-delete or re-parent orphans.
--   3. Apply this migration manually against Neon.
--
-- Cascade policy summary:
--   Deleting a client     -> RESTRICT if ACTIVE projects exist;
--                            SET NULL on leads (lead remains but loses link);
--                            CASCADE on client-only data (notifications scoped to client).
--   Deleting a project    -> CASCADE milestones/tasks/files/messages.
--   Deleting a milestone  -> SET NULL task.milestone_id (tasks remain).
--   Deleting a lead       -> SET NULL assistant_sessions.captured_lead_id.
--   Public portfolio projects (projects table) are independent of clients;
--   client_projects.public_project_id is SET NULL on project delete.

-- 1. Client identity
ALTER TABLE "client_projects"
  ADD CONSTRAINT "cp_client_fk" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT;

ALTER TABLE "invoices"
  ADD CONSTRAINT "inv_client_fk" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT;

ALTER TABLE "project_files"
  ADD CONSTRAINT "pf_client_fk" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL;

ALTER TABLE "notifications"
  ADD CONSTRAINT "n_client_fk" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE;

-- 2. Client projects
ALTER TABLE "milestones"
  ADD CONSTRAINT "ms_project_fk" FOREIGN KEY ("project_id") REFERENCES "client_projects"("id") ON DELETE CASCADE;

ALTER TABLE "tasks"
  ADD CONSTRAINT "tk_project_fk" FOREIGN KEY ("project_id") REFERENCES "client_projects"("id") ON DELETE CASCADE;

ALTER TABLE "project_files"
  ADD CONSTRAINT "pf_project_fk" FOREIGN KEY ("project_id") REFERENCES "client_projects"("id") ON DELETE CASCADE;

ALTER TABLE "messages"
  ADD CONSTRAINT "msg_ctx_project_fk" FOREIGN KEY ("context_id") REFERENCES "client_projects"("id") ON DELETE CASCADE
  DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "invoices"
  ADD CONSTRAINT "inv_project_fk" FOREIGN KEY ("project_id") REFERENCES "client_projects"("id") ON DELETE SET NULL;

ALTER TABLE "client_projects"
  ADD CONSTRAINT "cp_public_fk" FOREIGN KEY ("public_project_id") REFERENCES "projects"("id") ON DELETE SET NULL;

-- 3. Milestones
ALTER TABLE "tasks"
  ADD CONSTRAINT "tk_milestone_fk" FOREIGN KEY ("milestone_id") REFERENCES "milestones"("id") ON DELETE SET NULL;

-- 4. Leads
ALTER TABLE "leads"
  ADD CONSTRAINT "lead_client_fk" FOREIGN KEY ("converted_client_id") REFERENCES "clients"("id") ON DELETE SET NULL;

-- Note: assistant_sessions.captured_lead_id references leads but messages.contextId
-- can point to leads too; we add those as FK once leads/convertedClientId is clean.
ALTER TABLE "assistant_sessions"
  ADD CONSTRAINT "as_lead_fk" FOREIGN KEY ("captured_lead_id") REFERENCES "leads"("id") ON DELETE SET NULL;

-- 5. Testimonials -> portfolio project
ALTER TABLE "testimonials"
  ADD CONSTRAINT "tm_proj_fk" FOREIGN KEY ("related_project_id") REFERENCES "projects"("id") ON DELETE SET NULL;

-- 6. Media (project-scoped files) -> client projects
ALTER TABLE "media"
  ADD CONSTRAINT "media_proj_fk" FOREIGN KEY ("project_id") REFERENCES "client_projects"("id") ON DELETE SET NULL;
ALTER TABLE "media"
  ADD CONSTRAINT "media_client_fk" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL;

-- 7. Ai usage -> assistant_sessions
ALTER TABLE "ai_usage"
  ADD CONSTRAINT "au_sess_fk" FOREIGN KEY ("session_id") REFERENCES "assistant_sessions"("id") ON DELETE SET NULL;
ALTER TABLE "ai_usage"
  ADD CONSTRAINT "au_client_fk" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL;

-- Orphan-reporting queries (run first; counts must all be 0 before FKs apply):
--   SELECT COUNT(*) FROM client_projects cp LEFT JOIN clients c ON c.id = cp.client_id WHERE c.id IS NULL;
--   SELECT COUNT(*) FROM milestones m    LEFT JOIN client_projects p ON p.id = m.project_id WHERE p.id IS NULL;
--   SELECT COUNT(*) FROM tasks t         LEFT JOIN client_projects p ON p.id = t.project_id WHERE p.id IS NULL;
--   SELECT COUNT(*) FROM project_files f LEFT JOIN client_projects p ON p.id = f.project_id WHERE p.id IS NULL;
--   SELECT COUNT(*) FROM messages m
--     WHERE m.context_type = 'PROJECT' AND m.context_id IS NOT NULL
--       AND NOT EXISTS (SELECT 1 FROM client_projects p WHERE p.id = m.context_id);
--   SELECT COUNT(*) FROM invoices i      LEFT JOIN clients c ON c.id = i.client_id WHERE c.id IS NULL;
--   SELECT COUNT(*) FROM leads l WHERE l.converted_client_id IS NOT NULL
--     AND NOT EXISTS (SELECT 1 FROM clients c WHERE c.id = l.converted_client_id);
--   SELECT COUNT(*) FROM testimonials t WHERE t.related_project_id IS NOT NULL
--     AND NOT EXISTS (SELECT 1 FROM projects p WHERE p.id = t.related_project_id);
$mig$);

-- ==== 0003_phase2_cms_crm ====
SELECT __apply_migration('0003_phase2_cms_crm', $mig$
-- Phase 2+3 migration: CMS + CRM foundation.
-- Apply after 0002_foreign_keys_manual.sql. Safe for existing databases; uses
-- IF NOT EXISTS / ADD VALUE IF NOT EXISTS throughout.

-- 1. New CMS tables.
CREATE TABLE IF NOT EXISTS "solutions" (
  "id" varchar(36) PRIMARY KEY NOT NULL,
  "slug" varchar(120) NOT NULL,
  "title" varchar(200) NOT NULL,
  "tagline" varchar(240),
  "description" text,
  "icon" varchar(60) DEFAULT 'Globe',
  "features" jsonb DEFAULT '[]'::jsonb,
  "benefits" jsonb DEFAULT '[]'::jsonb,
  "image_url" varchar(500),
  "related_service_ids" jsonb DEFAULT '[]'::jsonb,
  "cta_label" varchar(60) DEFAULT 'Learn more',
  "cta_url" varchar(240),
  "is_published" boolean DEFAULT false NOT NULL,
  "is_featured" boolean DEFAULT false NOT NULL,
  "order" integer DEFAULT 0 NOT NULL,
  "seo_title" varchar(200),
  "seo_description" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "solutions_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tools" (
  "id" varchar(36) PRIMARY KEY NOT NULL,
  "name" varchar(120) NOT NULL,
  "category" varchar(40) DEFAULT 'Development' NOT NULL,
  "logo_url" varchar(500),
  "description" text,
  "website_url" varchar(500),
  "is_published" boolean DEFAULT true NOT NULL,
  "order" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "tools_name_unique" UNIQUE("name")
);
--> statement-breakpoint
-- 2. Lead notes (activity timeline).
CREATE TABLE IF NOT EXISTS "lead_notes" (
  "id" varchar(36) PRIMARY KEY NOT NULL,
  "lead_id" varchar(36) NOT NULL,
  "author_type" varchar(16) DEFAULT 'admin' NOT NULL,
  "author_id" varchar(128),
  "author_name" varchar(160),
  "type" varchar(30) DEFAULT 'note' NOT NULL,
  "body" text NOT NULL,
  "meta" jsonb DEFAULT '{}'::jsonb,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ln_lead_idx" ON "lead_notes" ("lead_id");
--> statement-breakpoint
-- 3. Page views (privacy-friendly analytics).
CREATE TABLE IF NOT EXISTS "page_views" (
  "id" varchar(36) PRIMARY KEY NOT NULL,
  "path" varchar(300) NOT NULL,
  "referrer" varchar(300),
  "anon_id" varchar(64),
  "country" varchar(8),
  "ua_hash" varchar(64),
  "session_id" varchar(64),
  "utm_source" varchar(80),
  "utm_medium" varchar(80),
  "utm_campaign" varchar(120),
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pv_path_idx" ON "page_views" ("path", "created_at");
--> statement-breakpoint
-- 4. Add ARCHIVED to lead_status enum (safe additive change).
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'ARCHIVED';
--> statement-breakpoint
-- 5. Extend leads with attribution + assignment fields.
ALTER TABLE leads ADD COLUMN IF NOT EXISTS source_page varchar(300);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS ai_ref varchar(64);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assigned_to varchar(128);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS last_contacted_at timestamp with time zone;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS converted_at timestamp with time zone;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS lead_assigned_idx ON leads (assigned_to);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS ins_slug_idx ON insights (slug);
CREATE UNIQUE INDEX IF NOT EXISTS tools_name_idx ON tools (name);
$mig$);

-- ==== 0004_phase4_operations ====
SELECT __apply_migration('0004_phase4_operations', $mig$
-- Migration 0004: Phase 4 — Client Project Workspace + Business Operations
-- Additive only — no destructive changes. Safe to run on existing DB.


-- 1) Extend project_status enum with new project-management states.
ALTER TYPE project_status ADD VALUE IF NOT EXISTS 'PLANNING';
ALTER TYPE project_status ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE project_status ADD VALUE IF NOT EXISTS 'ON_HOLD';
ALTER TYPE project_status ADD VALUE IF NOT EXISTS 'REVIEW';
ALTER TYPE project_status ADD VALUE IF NOT EXISTS 'CANCELLED';

-- 2) Extend milestone_status enum.
ALTER TYPE milestone_status ADD VALUE IF NOT EXISTS 'REJECTED';

-- 3) New enums for invoices, payments, tasks, messages.
DO $$ BEGIN
  CREATE TYPE invoice_status AS ENUM
    ('DRAFT','SENT','VIEWED','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED','VOID');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE payment_status AS ENUM
    ('PENDING','SUCCESSFUL','FAILED','REFUNDED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE task_priority AS ENUM ('LOW','MEDIUM','HIGH','URGENT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE invoice_item_kind AS ENUM
    ('SERVICE','MILESTONE','HOURLY','PRODUCT','DISCOUNT','TAX','CUSTOM');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 4) New columns on client_projects (project management).
ALTER TABLE client_projects ADD COLUMN IF NOT EXISTS priority task_priority NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE client_projects ADD COLUMN IF NOT EXISTS assignee varchar(128);
ALTER TABLE client_projects ADD COLUMN IF NOT EXISTS total_cents integer DEFAULT 0;
ALTER TABLE client_projects ADD COLUMN IF NOT EXISTS currency varchar(3) NOT NULL DEFAULT 'USD';
ALTER TABLE client_projects ADD COLUMN IF NOT EXISTS archived_at timestamptz;

-- 5) New columns on milestones.
ALTER TABLE milestones ADD COLUMN IF NOT EXISTS amount_cents integer;
ALTER TABLE milestones ADD COLUMN IF NOT EXISTS approved_at timestamptz;
ALTER TABLE milestones ADD COLUMN IF NOT EXISTS approved_by varchar(128);
ALTER TABLE milestones ADD COLUMN IF NOT EXISTS rejection_reason text;

-- 6) New columns on tasks.
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS priority task_priority NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS completed_at timestamptz;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS completed_by varchar(128);

-- 7) New columns on project_files.
ALTER TABLE project_files ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE project_files ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE project_files ADD COLUMN IF NOT EXISTS replace_of varchar(36);

-- 8) New columns on messages (two-way, read state, recipients).
ALTER TABLE messages ADD COLUMN IF NOT EXISTS to_uid varchar(128);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS to_client_id varchar(36);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS to_name varchar(160);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS thread_id varchar(36);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS read_at timestamptz;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS is_from_client boolean NOT NULL DEFAULT false;
ALTER TABLE messages DROP COLUMN IF EXISTS is_read;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS is_read boolean NOT NULL DEFAULT false;
CREATE INDEX IF NOT EXISTS msg_thread_idx ON messages(thread_id);
CREATE INDEX IF NOT EXISTS msg_to_admin_idx ON messages(to_uid, is_read);
CREATE INDEX IF NOT EXISTS msg_to_client_idx ON messages(to_client_id, is_read);

-- 9) Milestone approvals (audit trail).
CREATE TABLE IF NOT EXISTS milestone_approvals (
  id varchar(36) PRIMARY KEY,
  milestone_id varchar(36) NOT NULL REFERENCES milestones(id) ON DELETE CASCADE,
  project_id varchar(36) NOT NULL,
  client_id varchar(36) NOT NULL,
  action varchar(20) NOT NULL,        -- APPROVED | REJECTED
  comment text,
  actor_type varchar(16) NOT NULL,    -- client|admin|system
  actor_id varchar(128),
  actor_name varchar(160),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ma_milestone_idx ON milestone_approvals(milestone_id);
CREATE INDEX IF NOT EXISTS ma_proj_idx ON milestone_approvals(project_id);

-- 10) Invoice items (line items).
CREATE TABLE IF NOT EXISTS invoice_items (
  id varchar(36) PRIMARY KEY,
  invoice_id varchar(36) NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  kind invoice_item_kind NOT NULL DEFAULT 'CUSTOM',
  description text NOT NULL,
  quantity numeric(12,2) NOT NULL DEFAULT 1,
  unit_price_cents integer NOT NULL DEFAULT 0,
  amount_cents integer NOT NULL DEFAULT 0,
  order_idx integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ii_invoice_idx ON invoice_items(invoice_id);

-- 11) Invoices: tighten columns, add indexes.
--    (Existing status is varchar; we leave the column as varchar for backward
--     compatibility but add a CHECK constraint for safety.)
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS tax_cents integer NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS discount_cents integer NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS subtotal_cents integer NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS issued_at timestamptz;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS viewed_at timestamptz;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS cancelled_at timestamptz;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS cancellation_reason text;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS inv_client_idx ON invoices(client_id);
CREATE INDEX IF NOT EXISTS inv_project_idx ON invoices(project_id);
CREATE INDEX IF NOT EXISTS inv_status_idx ON invoices(status);

-- 12) Payments.
CREATE TABLE IF NOT EXISTS payments (
  id varchar(36) PRIMARY KEY,
  invoice_id varchar(36) REFERENCES invoices(id) ON DELETE SET NULL,
  client_id varchar(36) NOT NULL,
  project_id varchar(36),
  provider varchar(32) NOT NULL DEFAULT 'flutterwave',    -- flutterwave|manual
  provider_ref varchar(160),                              -- tx_ref / flw_ref
  provider_transaction_id varchar(160),                   -- Flutterwave transaction id
  amount_cents integer NOT NULL,
  currency varchar(3) NOT NULL DEFAULT 'USD',
  status payment_status NOT NULL DEFAULT 'PENDING',
  verified_at timestamptz,
  verification_meta jsonb DEFAULT '{}'::jsonb,
  failure_reason text,
  idempotency_key varchar(128) UNIQUE,                    -- for duplicate protection
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS pay_client_idx ON payments(client_id);
CREATE INDEX IF NOT EXISTS pay_invoice_idx ON payments(invoice_id);
CREATE INDEX IF NOT EXISTS pay_provider_ref_idx ON payments(provider_ref);

-- 13) Indexes for common lookups.
CREATE INDEX IF NOT EXISTS ms_proj_status_idx ON milestones(project_id, status);
CREATE INDEX IF NOT EXISTS tk_proj_status_idx ON tasks(project_id, status);
CREATE INDEX IF NOT EXISTS pf_proj_vis_idx ON project_files(project_id, deleted_at);
CREATE INDEX IF NOT EXISTS n_unread_client_idx ON notifications(client_id, is_read) WHERE client_id IS NOT NULL;

-- 14) Add audit actions for new Phase 4 events.
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'MILESTONE_APPROVE';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'MILESTONE_REJECT';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'INVOICE_SEND';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'INVOICE_VIEW';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'PAYMENT_VERIFY';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'MESSAGE_SEND';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'NOTIFICATION_READ';

$mig$);

COMMIT;

-- =====================================================================
-- SEED: default site_settings (only runs if empty)
-- =====================================================================
BEGIN;
INSERT INTO site_settings (key, value)
VALUES ('site', jsonb_build_object(
  'company', jsonb_build_object('name','Toluene Tech','email','hello@toluenetech.com'),
  'contact', jsonb_build_object('email','hello@toluenetech.com'),
  'availability', 'AVAILABLE',
  'hero', jsonb_build_object(
    'title','Ship software that actually works.',
    'subtitle','Toluene Tech designs, builds and operates production-grade web, mobile and AI systems.',
    'primaryCta','Start a project',
    'primaryCtaHref','/start-project'
  ),
  'seo_defaults', jsonb_build_object(
    'siteName','Toluene Tech',
    'defaultTitle','Toluene Tech — Web, Mobile & AI Engineering'
  )
))
ON CONFLICT (key) DO NOTHING;
COMMIT;
